/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleProduto;
import Modelo.ModeloProduto;
import Modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Usuario
 */
public class FrmProdutos extends javax.swing.JFrame {
    
    ConectaBanco conexao = new ConectaBanco();
    ConectaBanco conexaoPesquisa = new ConectaBanco();
    ModeloProduto mod = new ModeloProduto();
    Controle.ControleProduto control = new ControleProduto();

    /**
     * Creates new form FrmProdutos
     */
    public FrmProdutos() {
        initComponents();
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelQuantidade = new javax.swing.JLabel();
        jLabelPrecodeCompra = new javax.swing.JLabel();
        jLabelPrecodeVenda = new javax.swing.JLabel();
        jLabelFornecedor = new javax.swing.JLabel();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldPrecodeCompra = new javax.swing.JTextField();
        jTextFieldPrecodeVenda = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaProdutos = new javax.swing.JTable();
        jButtonADDFornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabelID.setText("ID:");

        jLabelNome.setText("Nome:");

        jLabelQuantidade.setText("Quantidade:");

        jLabelPrecodeCompra.setText("Preço de Compra:");

        jLabelPrecodeVenda.setText("Preço de Venda:");

        jLabelFornecedor.setText("Fornecedor:");

        jComboBoxFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldID.setEnabled(false);

        jTextFieldNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNome.setEnabled(false);

        jTextFieldQuantidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldQuantidade.setEnabled(false);

        jTextFieldPrecodeCompra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrecodeCompra.setEnabled(false);

        jTextFieldPrecodeVenda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrecodeVenda.setEnabled(false);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTableTabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTabelaProdutos);

        jButtonADDFornecedor.setText("+");
        jButtonADDFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPrecodeCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrecodeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jButtonEditar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPrecodeVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrecodeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonADDFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButtonExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPesquisar)
                                .addGap(5, 5, 5)
                                .addComponent(jButtonPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSair))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNome)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelQuantidade)
                        .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelID)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecodeCompra)
                    .addComponent(jLabelPrecodeVenda)
                    .addComponent(jLabelFornecedor)
                    .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecodeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecodeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonADDFornecedor))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonSair)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(825, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDFornecedorActionPerformed
        // TODO add your handling code here:
        FrmFornecedores frm = new FrmFornecedores();
        frm.setVisible(true);
        preencherCombo();
    }//GEN-LAST:event_jButtonADDFornecedorActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        mod.setFornecedorProduto((String) jComboBoxFornecedor.getSelectedItem());
        mod.setNomeProduto(jTextFieldNome.getText());
        mod.setPrecoCompra(Float.parseFloat(jTextFieldPrecodeCompra.getText()));
        mod.setPrecoVenda(Float.parseFloat(jTextFieldPrecodeVenda.getText()));
        mod.setQtdProduto(Integer.parseInt(jTextFieldQuantidade.getText()));
        control.inserirProduto(mod);
        jTextFieldNome.setEnabled(!true);
        jTextFieldQuantidade.setEnabled(!true);
        jTextFieldPrecodeCompra.setEnabled(!true);
        jTextFieldPrecodeVenda.setEnabled(!true);
        jTextFieldID.setText("");
        jTextFieldPesquisar.setText("");
        jTextFieldNome.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldPrecodeCompra.setText("");
        jTextFieldPrecodeVenda.setText("");
        jButtonSalvar.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonCancelar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
//        mod.setPesquisa(jTextFieldPesquisar.getText());
//        ModeloProduto model = control.buscaProduto(mod);
//        jTextFieldID.setText(String.valueOf(model.getIdProduto()));
//        jTextFieldNome.setText(model.getNomeProduto());
//        jTextFieldQuantidade.setText(String.valueOf(model.getQtdProduto()));
//        jTextFieldPrecodeCompra.setText(String.valueOf(model.getPrecoCompra()));
//        jTextFieldPrecodeVenda.setText(String.valueOf(model.getPrecoVenda()));
//        jComboBoxFornecedor.setSelectedItem(model.getFornecedorProduto());
        
        preencherTabela("select * from produto where nome_produto like'%" + jTextFieldPesquisar.getText() + "%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        mod.setIdProduto(Integer.parseInt(jTextFieldID.getText()));
        mod.setFornecedorProduto((String) jComboBoxFornecedor.getSelectedItem());
        mod.setNomeProduto(jTextFieldNome.getText());
        mod.setPrecoCompra(Float.parseFloat(jTextFieldPrecodeCompra.getText()));
        mod.setPrecoVenda(Float.parseFloat(jTextFieldPrecodeVenda.getText()));
        mod.setQtdProduto(Integer.parseInt(jTextFieldQuantidade.getText()));
        control.editaProduto(mod);
        jTextFieldNome.setEnabled(!true);
        jTextFieldQuantidade.setEnabled(!true);
        jTextFieldPrecodeCompra.setEnabled(!true);
        jTextFieldPrecodeVenda.setEnabled(!true);
        jTextFieldID.setText("");
        jTextFieldPesquisar.setText("");
        jTextFieldNome.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldPrecodeCompra.setText("");
        jTextFieldPrecodeVenda.setText("");
        jButtonSalvar.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonCancelar.setEnabled(false);
        preencherTabela("");
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        mod.setIdProduto(Integer.parseInt(jTextFieldID.getText()));
        control.excluirProduto(mod);
        jTextFieldNome.setEnabled(!true);
        jTextFieldQuantidade.setEnabled(!true);
        jTextFieldPrecodeCompra.setEnabled(!true);
        jTextFieldPrecodeVenda.setEnabled(!true);
        jTextFieldID.setText("");
        jTextFieldPesquisar.setText("");
        jTextFieldNome.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldPrecodeCompra.setText("");
        jTextFieldPrecodeVenda.setText("");
        jButtonSalvar.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonCancelar.setEnabled(false);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        jTextFieldNome.setEnabled(true);
        jTextFieldQuantidade.setEnabled(true);
        jTextFieldPrecodeCompra.setEnabled(true);
        jTextFieldPrecodeVenda.setEnabled(true);
        jTextFieldID.setText("");
        jTextFieldPesquisar.setText("");
        jTextFieldNome.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldPrecodeCompra.setText("");
        jTextFieldPrecodeVenda.setText("");
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
       jTextFieldNome.setEnabled(!true);
        jTextFieldQuantidade.setEnabled(!true);
        jTextFieldPrecodeCompra.setEnabled(!true);
        jTextFieldPrecodeVenda.setEnabled(!true);
        jTextFieldID.setText("");
        jTextFieldPesquisar.setText("");
        jTextFieldNome.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldPrecodeCompra.setText("");
        jTextFieldPrecodeVenda.setText("");
        jButtonSalvar.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonCancelar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableTabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTabelaProdutosMouseClicked
        // TODO add your handling code here:
            String nome_produto = ""+jTableTabelaProdutos.getValueAt(jTableTabelaProdutos.getSelectedRow(), 0);
            conexao.conexao();
            conexaoPesquisa.conexao();
            conexao.executaSQL("select * from produto where nome_produto ='"+nome_produto+"'");
        try {
            conexao.rs.first();
            jTextFieldID.setText(String.valueOf(conexao.rs.getInt("id_produto")));
            jTextFieldNome.setText(conexao.rs.getString("nome_produto"));
            jTextFieldQuantidade.setText(String.valueOf(conexao.rs.getInt("quantidade")));
            jTextFieldPrecodeCompra.setText(String.valueOf(conexao.rs.getFloat("preco_compra")));
            jTextFieldPrecodeVenda.setText(String.valueOf(conexao.rs.getFloat("preco_venda")));
            conexaoPesquisa.executaSQL("Select * from fornecedores where id_fornecedor="+conexao.rs.getInt("id_fornecedor"));
            conexaoPesquisa.rs.first();
            jComboBoxFornecedor.setSelectedItem(conexaoPesquisa.rs.getString("nome_fornecedor"));
            conexao.desconecta();
            jTextFieldNome.setEnabled(true);
            jTextFieldQuantidade.setEnabled(true);
            jTextFieldPrecodeCompra.setEnabled(true);
            jTextFieldPrecodeVenda.setEnabled(true);
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            //JOptionPane.showMessageDialog(rootPane, nome_produto);
        } catch (SQLException ex) {
            conexaoPesquisa.desconecta();
            conexao.desconecta();
            //JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar os dados!\Erro:" + s);
        }
    }//GEN-LAST:event_jTableTabelaProdutosMouseClicked

    public void preencherCombo(){
        conexao.conexao();
        conexao.executaSQL("select* from fornecedores order by nome_fornecedor");
        try {
            conexao.rs.first();
           jComboBoxFornecedor.removeAllItems();
            do{
                jComboBoxFornecedor.addItem(conexao.rs.getString("nome_fornecedor"));
                    }while(conexao.rs.next());
            conexao.desconecta();
                    }catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combobox\nERRO:"+ ex);
            conexao.desconecta();
        }
    
    }
    
    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        conexao.conexao();
        String []Colunas = new String []{"Nome Produto","Quantidade","Preço"};
        
        conexao.executaSQL(SQL);
        try {
            conexao.rs.first();
            do {
                dados.add(new Object []{conexao.rs.getString("nome_produto"), conexao.rs.getString("quantidade"), conexao.rs.getString("preco_venda")}); 
            }while (conexao.rs.next());   
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro ao preencher tabela!\nERRO:" + ex);
                }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableTabelaProdutos.setModel(modelo);
        jTableTabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(180);
        jTableTabelaProdutos.getColumnModel().getColumn(0).setResizable(false);
        jTableTabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(367);
        jTableTabelaProdutos.getColumnModel().getColumn(1).setResizable(false);
        jTableTabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(180);
        jTableTabelaProdutos.getColumnModel().getColumn(2).setResizable(false);
        jTableTabelaProdutos.getTableHeader().setReorderingAllowed(false);
        jTableTabelaProdutos.setAutoResizeMode(jTableTabelaProdutos.AUTO_RESIZE_OFF);
        jTableTabelaProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADDFornecedor;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFornecedor;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPrecodeCompra;
    private javax.swing.JLabel jLabelPrecodeVenda;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaProdutos;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPrecodeCompra;
    private javax.swing.JTextField jTextFieldPrecodeVenda;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
